In [1]:
# 메모리가 클 경우 Queue Runners를 사용할 수 있다.
# 여러개의 파일을 Queue에 쌓고 Reader로 연결해서 Decoding 후 Queue에 쌓는다.
# 이후 Queue에서 하나씩 꺼내서 사용하게 된다.

# 1. 파일들의 리스트를 만들어 준다.
# 2. 파일을 읽어올 Reader를 정의한다. 그림에서는 TextLineReader를 사용했다.
# 3. value 값을 어떻게 decode 할것인가에 대해 알아본다.

In [2]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility


In [3]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')


In [4]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [5]:
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [6]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [7]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [8]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [9]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b


In [10]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [11]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [12]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [13]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [14]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  29521.465 
Prediction:
 [[ -2.0228353]
 [-11.679093 ]
 [ -6.314896 ]
 [-11.964677 ]
 [ -7.0291677]
 [-14.155648 ]
 [-13.960649 ]
 [-17.062798 ]
 [-19.29863  ]
 [-29.977287 ]]
10 Cost:  128.26868 
Prediction:
 [[159.30743]
 [182.31711]
 [184.78253]
 [196.18796]
 [140.9202 ]
 [ 94.98316]
 [141.8722 ]
 [ 98.49206]
 [162.06638]
 [138.09213]]
20 Cost:  116.42484 
Prediction:
 [[160.35823]
 [183.64087]
 [186.05333]
 [197.59856]
 [141.92296]
 [ 95.77059]
 [142.95056]
 [ 99.32114]
 [163.35014]
 [139.34541]]
30 Cost:  115.3063 
Prediction:
 [[160.32764]
 [183.66434]
 [186.04324]
 [197.61401]
 [141.93405]
 [ 95.8266 ]
 [142.98453]
 [ 99.37588]
 [163.41837]
 [139.47243]]
40 Cost:  114.261185 
Prediction:
 [[160.28986 ]
 [183.67892 ]
 [186.02458 ]
 [197.62    ]
 [141.93835 ]
 [ 95.877426]
 [143.01134 ]
 [ 99.425156]
 [163.47807 ]
 [139.59128 ]]
50 Cost:  113.22609 
Prediction:
 [[160.25229]
 [183.69342]
 [186.00595]
 [197.62593]
 [141.94263]
 [ 95.92798]
 [143.038  ]
 [ 99.47428]
 [163.53

500 Cost:  75.44438 
Prediction:
 [[158.74178 ]
 [184.26134 ]
 [185.24951 ]
 [197.87093 ]
 [142.08635 ]
 [ 97.96213 ]
 [144.14262 ]
 [101.510475]
 [165.92732 ]
 [144.49928 ]]
510 Cost:  74.77345 
Prediction:
 [[158.71196]
 [184.27228]
 [185.23442]
 [197.87595]
 [142.08862]
 [ 98.00238]
 [144.16519]
 [101.55211]
 [165.97462]
 [144.59474]]
520 Cost:  74.10888 
Prediction:
 [[158.68227 ]
 [184.28311 ]
 [185.21936 ]
 [197.88092 ]
 [142.09082 ]
 [ 98.042435]
 [144.18765 ]
 [101.59358 ]
 [166.02167 ]
 [144.68974 ]]
530 Cost:  73.450516 
Prediction:
 [[158.65273]
 [184.29391]
 [185.2044 ]
 [197.88593]
 [142.093  ]
 [ 98.0823 ]
 [144.21007]
 [101.63492]
 [166.0685 ]
 [144.7843 ]]
540 Cost:  72.7984 
Prediction:
 [[158.62335 ]
 [184.30463 ]
 [185.18948 ]
 [197.89085 ]
 [142.09511 ]
 [ 98.12195 ]
 [144.23238 ]
 [101.676094]
 [166.11508 ]
 [144.87842 ]]
550 Cost:  72.15238 
Prediction:
 [[158.59409 ]
 [184.31525 ]
 [185.17464 ]
 [197.8958  ]
 [142.09721 ]
 [ 98.161415]
 [144.2546  ]
 [101.71714 ]

1000 Cost:  48.57907 
Prediction:
 [[157.42036]
 [184.7304 ]
 [184.57205]
 [198.10063]
 [142.15718]
 [ 99.74799]
 [145.17654]
 [103.4211 ]
 [168.02525]
 [148.76543]]
1010 Cost:  48.16065 
Prediction:
 [[157.39722 ]
 [184.73831 ]
 [184.56003 ]
 [198.10483 ]
 [142.15784 ]
 [ 99.77936 ]
 [145.1954  ]
 [103.455986]
 [168.06209 ]
 [148.841   ]]
1020 Cost:  47.746185 
Prediction:
 [[157.37419]
 [184.74617]
 [184.54803]
 [198.109  ]
 [142.15846]
 [ 99.81056]
 [145.21417]
 [103.49074]
 [168.09874]
 [148.91623]]
1030 Cost:  47.3357 
Prediction:
 [[157.35127 ]
 [184.754   ]
 [184.53612 ]
 [198.11317 ]
 [142.15906 ]
 [ 99.841606]
 [145.2329  ]
 [103.52537 ]
 [168.13522 ]
 [148.99107 ]]
1040 Cost:  46.929016 
Prediction:
 [[157.32846]
 [184.76172]
 [184.5242 ]
 [198.11728]
 [142.1596 ]
 [ 99.87248]
 [145.25153]
 [103.55988]
 [168.17148]
 [149.06558]]
1050 Cost:  46.526093 
Prediction:
 [[157.30579 ]
 [184.76944 ]
 [184.5124  ]
 [198.12143 ]
 [142.16014 ]
 [ 99.90323 ]
 [145.27011 ]
 [103.594284]
 

1520 Cost:  31.3128 
Prediction:
 [[156.36101]
 [185.0785 ]
 [184.01317]
 [198.30016]
 [142.15887]
 [101.18602]
 [146.07318]
 [105.08254]
 [169.71437]
 [152.26172]]
1530 Cost:  31.056965 
Prediction:
 [[156.34328]
 [185.08405]
 [184.00365]
 [198.30363]
 [142.15833]
 [101.21014]
 [146.08885]
 [105.11165]
 [169.74269]
 [152.32097]]
1540 Cost:  30.803623 
Prediction:
 [[156.32567]
 [185.08955]
 [183.9942 ]
 [198.30713]
 [142.15778]
 [101.23413]
 [146.10449]
 [105.14065]
 [169.77087]
 [152.37993]]
1550 Cost:  30.552662 
Prediction:
 [[156.3081 ]
 [185.095  ]
 [183.98477]
 [198.3106 ]
 [142.15721]
 [101.25799]
 [146.12007]
 [105.16954]
 [169.7989 ]
 [152.4386 ]]
1560 Cost:  30.304071 
Prediction:
 [[156.29068]
 [185.1004 ]
 [183.97539]
 [198.31404]
 [142.1566 ]
 [101.28174]
 [146.13557]
 [105.19835]
 [169.82678]
 [152.49701]]
1570 Cost:  30.05775 
Prediction:
 [[156.27332]
 [185.10577]
 [183.96605]
 [198.31747]
 [142.156  ]
 [101.30537]
 [146.15103]
 [105.22705]
 [169.85454]
 [152.55516]]
1

In [15]:
coord.request_stop()
coord.join(threads)


In [16]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Your score will be  [[177.78145]]
Other scores will be  [[141.10997]
 [191.17378]]
