In [2]:
# 파일에서 데이터를 로딩하는 예제이다

In [3]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
import numpy as np
tf.set_random_seed(777)  # for reproducibility

In [4]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]


In [5]:
# Make sure the shape and data are OK
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [6]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [7]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b


In [9]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  21027.002 
Prediction:
 [[22.048063 ]
 [21.619787 ]
 [24.096693 ]
 [22.293005 ]
 [18.633902 ]
 [ 7.2669735]
 [12.33103  ]
 [ 3.150511 ]
 [14.347944 ]
 [ 4.2534237]
 [14.485708 ]
 [10.678068 ]
 [28.80464  ]
 [29.298803 ]
 [11.237837 ]
 [18.646544 ]
 [31.189451 ]
 [13.344664 ]
 [28.841742 ]
 [25.66281  ]
 [15.084761 ]
 [16.798368 ]
 [15.924551 ]
 [31.36112  ]
 [24.986364 ]]
10 Cost:  95.97634 
Prediction:
 [[157.11063]
 [183.99281]
 [184.06302]
 [196.52917]
 [142.46274]
 [ 98.59757]
 [142.77235]
 [ 99.8778 ]
 [166.13176]
 [144.8915 ]
 [140.14995]
 [134.61139]
 [194.05147]
 [166.64041]
 [142.28706]
 [183.43298]
 [161.97667]
 [169.89073]
 [186.37146]
 [166.61377]
 [168.04634]
 [169.14368]
 [161.75204]
 [167.48862]
 [193.25117]]
20 Cost:  94.257256 
Prediction:
 [[158.01503 ]
 [185.11975 ]
 [185.15112 ]
 [197.73497 ]
 [143.315   ]
 [ 99.26257 ]
 [143.69464 ]
 [100.587845]
 [167.21953 ]
 [145.9485  ]
 [141.02908 ]
 [135.50377 ]
 [195.15509 ]
 [167.5308  ]
 [143.2218  ]
 [184.59265 ]

250 Cost:  79.26501 
Prediction:
 [[157.3954  ]
 [185.23462 ]
 [184.78404 ]
 [197.78937 ]
 [143.24155 ]
 [100.009895]
 [144.1698  ]
 [101.522026]
 [168.08138 ]
 [147.82777 ]
 [141.27661 ]
 [136.30139 ]
 [194.32542 ]
 [166.2489  ]
 [143.87785 ]
 [185.06287 ]
 [161.30603 ]
 [171.6594  ]
 [186.41858 ]
 [166.64485 ]
 [169.6451  ]
 [170.71495 ]
 [163.06464 ]
 [166.6772  ]
 [194.1729  ]]
260 Cost:  78.67659 
Prediction:
 [[157.36978 ]
 [185.23882 ]
 [184.76862 ]
 [197.79132 ]
 [143.23795 ]
 [100.040306]
 [144.18938 ]
 [101.56084 ]
 [168.11636 ]
 [147.90483 ]
 [141.28662 ]
 [136.33392 ]
 [194.29085 ]
 [166.19562 ]
 [143.90485 ]
 [185.08179 ]
 [161.24333 ]
 [171.68665 ]
 [186.3772  ]
 [166.60747 ]
 [169.66641 ]
 [170.73499 ]
 [163.07661 ]
 [166.60791 ]
 [194.1629  ]]
270 Cost:  78.09314 
Prediction:
 [[157.3443 ]
 [185.24297]
 [184.75323]
 [197.79329]
 [143.23434]
 [100.07057]
 [144.20892]
 [101.59955]
 [168.15117]
 [147.98152]
 [141.29663]
 [136.36627]
 [194.25641]
 [166.14258]
 [143.93173]
 

550 Cost:  63.59115 
Prediction:
 [[156.68053]
 [185.34528]
 [184.34969]
 [197.84714]
 [143.12907]
 [100.85953]
 [144.7305 ]
 [102.63244]
 [169.05846]
 [149.99304]
 [141.56075]
 [137.21312]
 [193.34966]
 [164.74326]
 [144.64479]
 [185.59166]
 [159.52829]
 [172.44289]
 [185.25453]
 [165.59477]
 [170.25288]
 [171.27512]
 [163.4105 ]
 [164.72742]
 [193.88492]]
560 Cost:  63.133408 
Prediction:
 [[156.65852]
 [185.34845]
 [184.33618]
 [197.849  ]
 [143.12518]
 [100.88571]
 [144.74828]
 [102.66758]
 [169.08855]
 [150.06021]
 [141.56967]
 [137.24133]
 [193.31923]
 [164.69623]
 [144.66887]
 [185.60794]
 [159.47253]
 [172.4678 ]
 [185.2183 ]
 [165.56218]
 [170.27203]
 [171.29239]
 [163.42155]
 [164.66681]
 [193.87573]]
570 Cost:  62.67941 
Prediction:
 [[156.63663 ]
 [185.35161 ]
 [184.32275 ]
 [197.85088 ]
 [143.12128 ]
 [100.911766]
 [144.76598 ]
 [102.70262 ]
 [169.11852 ]
 [150.1271  ]
 [141.57854 ]
 [137.26944 ]
 [193.28894 ]
 [164.6494  ]
 [144.6929  ]
 [185.62418 ]
 [159.41704 ]
 [172.4

780 Cost:  53.969013 
Prediction:
 [[156.20166]
 [185.41087]
 [184.054  ]
 [197.88963]
 [143.03766]
 [101.42969]
 [145.12471]
 [103.41231]
 [169.71397]
 [151.46346]
 [141.75722]
 [137.8296 ]
 [192.68176]
 [163.70937]
 [145.17691]
 [185.94656]
 [158.29976]
 [172.99773]
 [184.46103]
 [164.88164]
 [170.67741]
 [171.65167]
 [163.65694]
 [163.39964]
 [193.68027]]
790 Cost:  53.590965 
Prediction:
 [[156.1821 ]
 [185.41338]
 [184.04182]
 [197.89143]
 [143.0336 ]
 [101.45301]
 [145.1412 ]
 [103.4449 ]
 [169.74078]
 [151.52396]
 [141.76538]
 [137.8549 ]
 [192.65417]
 [163.66663]
 [145.19904]
 [185.96109]
 [158.2488 ]
 [173.021  ]
 [184.42834]
 [164.85231]
 [170.69511]
 [171.66708]
 [163.66731]
 [163.34497]
 [193.67166]]
800 Cost:  53.21599 
Prediction:
 [[156.16263]
 [185.41588]
 [184.0297 ]
 [197.89325]
 [143.02956]
 [101.47621]
 [145.15762]
 [103.47738]
 [169.76746]
 [151.5842 ]
 [141.7735 ]
 [137.8801 ]
 [192.62672]
 [163.62404]
 [145.22107]
 [185.97554]
 [158.19803]
 [173.0442 ]
 [184.3958

1210 Cost:  40.23095 
Prediction:
 [[155.44481 ]
 [185.49634 ]
 [183.57652 ]
 [197.96495 ]
 [142.85896 ]
 [102.333015]
 [145.78746 ]
 [104.72192 ]
 [170.75221 ]
 [153.83029 ]
 [142.0809  ]
 [138.81621 ]
 [191.59567 ]
 [162.02122 ]
 [146.0573  ]
 [186.50903 ]
 [156.2776  ]
 [173.93869 ]
 [183.17766 ]
 [163.73376 ]
 [171.38554 ]
 [172.24966 ]
 [164.07793 ]
 [161.25484 ]
 [193.33173 ]]
1220 Cost:  39.965763 
Prediction:
 [[155.42914 ]
 [185.49782 ]
 [183.56647 ]
 [197.96663 ]
 [142.85474 ]
 [102.35175 ]
 [145.80183 ]
 [104.750244]
 [170.77374 ]
 [153.87997 ]
 [142.0878  ]
 [138.83684 ]
 [191.5727  ]
 [161.9854  ]
 [146.07613 ]
 [186.52069 ]
 [156.23444 ]
 [173.95918 ]
 [183.1506  ]
 [163.70967 ]
 [171.40079 ]
 [172.26208 ]
 [164.08714 ]
 [161.20969 ]
 [193.32413 ]]
1230 Cost:  39.702797 
Prediction:
 [[155.41354]
 [185.49928]
 [183.55647]
 [197.96834]
 [142.8505 ]
 [102.37041]
 [145.81613]
 [104.77849]
 [170.79518]
 [153.92944]
 [142.0947 ]
 [138.85736]
 [191.54982]
 [161.94975]
 [146.094

1680 Cost:  29.84071 
Prediction:
 [[154.79005]
 [185.54553]
 [183.1497 ]
 [198.04118]
 [142.65784]
 [103.11744]
 [146.4148 ]
 [105.95944]
 [171.65335]
 [155.93591]
 [142.37875]
 [139.68639]
 [190.61469]
 [160.48734]
 [146.87227]
 [186.99765]
 [154.4189 ]
 [174.83972]
 [182.02759]
 [162.71254]
 [172.04861]
 [172.7708 ]
 [164.48491]
 [159.33646]
 [192.99612]]
1690 Cost:  29.66001 
Prediction:
 [[154.77783]
 [185.54616]
 [183.14156]
 [198.04274]
 [142.65355]
 [103.13215]
 [146.42714]
 [105.98379]
 [171.67024]
 [155.97595]
 [142.38452]
 [139.70284]
 [190.59587]
 [160.45781]
 [146.88812]
 [187.00679]
 [154.38287]
 [174.85756]
 [182.0056 ]
 [162.6931 ]
 [172.0616 ]
 [172.78058]
 [164.49301]
 [159.29987]
 [192.98947]]
1700 Cost:  29.480701 
Prediction:
 [[154.76566 ]
 [185.54677 ]
 [183.13347 ]
 [198.04428 ]
 [142.64925 ]
 [103.14677 ]
 [146.43947 ]
 [106.008064]
 [171.68703 ]
 [156.01581 ]
 [142.39027 ]
 [139.71922 ]
 [190.57712 ]
 [160.42839 ]
 [146.90393 ]
 [187.01591 ]
 [154.34698 ]
 [17

In [13]:
# Ask my score
print("Your score will be ", sess.run(
    hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ", sess.run(hypothesis,
                                        feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))

Your score will be  [[181.73277]]
Other scores will be  [[145.86266]
 [187.2313 ]]
