In [1]:
# 아래의 예제는 매트릭스를 사용한 예제이다.

In [11]:
# Lab 4 Multi-variable linear regression
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility

In [2]:
x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]

In [5]:
# placeholders for a tensor that will be always fed.
# N개를 예측 할때는 None, elemets는 갯수를 표시
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [4]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [6]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

In [7]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [8]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [9]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [10]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  22655.951 
Prediction:
 [[22.048063]
 [21.619787]
 [24.096693]
 [22.293005]
 [18.633902]]
10 Cost:  6.041753 
Prediction:
 [[155.17455]
 [181.64264]
 [181.76219]
 [193.98837]
 [140.6934 ]]
20 Cost:  5.813164 
Prediction:
 [[155.56952]
 [182.1321 ]
 [182.23676]
 [194.50674]
 [141.06909]]
30 Cost:  5.7920403 
Prediction:
 [[155.56291]
 [182.13885]
 [182.23573]
 [194.50717]
 [141.0766 ]]
40 Cost:  5.771007 
Prediction:
 [[155.55511]
 [182.14413]
 [182.23325]
 [194.50604]
 [141.08298]]
50 Cost:  5.7501135 
Prediction:
 [[155.54735]
 [182.1494 ]
 [182.23079]
 [194.50493]
 [141.08934]]
60 Cost:  5.7293425 
Prediction:
 [[155.53958]
 [182.15462]
 [182.2283 ]
 [194.50377]
 [141.09566]]
70 Cost:  5.7086334 
Prediction:
 [[155.53186]
 [182.15988]
 [182.22586]
 [194.50269]
 [141.10197]]
80 Cost:  5.6880617 
Prediction:
 [[155.52414]
 [182.1651 ]
 [182.22343]
 [194.50157]
 [141.10829]]
90 Cost:  5.667586 
Prediction:
 [[155.51643]
 [182.1703 ]
 [182.22098]
 [194.50044]
 [141.11455]]
100 C

1130 Cost:  4.023662 
Prediction:
 [[154.81631]
 [182.64343]
 [181.99771]
 [194.40657]
 [141.67844]]
1140 Cost:  4.0117006 
Prediction:
 [[154.81047]
 [182.6474 ]
 [181.99583]
 [194.40587]
 [141.6831 ]]
1150 Cost:  3.999823 
Prediction:
 [[154.80461]
 [182.65132]
 [181.99396]
 [194.40514]
 [141.68771]]
1160 Cost:  3.9879932 
Prediction:
 [[154.7988 ]
 [182.65526]
 [181.9921 ]
 [194.40445]
 [141.69234]]
1170 Cost:  3.9762325 
Prediction:
 [[154.79298]
 [182.65916]
 [181.9902 ]
 [194.40372]
 [141.69691]]
1180 Cost:  3.9645054 
Prediction:
 [[154.78719]
 [182.6631 ]
 [181.98837]
 [194.40303]
 [141.70152]]
1190 Cost:  3.9528553 
Prediction:
 [[154.78139]
 [182.66698]
 [181.9865 ]
 [194.40231]
 [141.70607]]
1200 Cost:  3.9412675 
Prediction:
 [[154.77562]
 [182.67087]
 [181.98466]
 [194.40163]
 [141.71065]]
1210 Cost:  3.9297395 
Prediction:
 [[154.7699 ]
 [182.67476]
 [181.98282]
 [194.40096]
 [141.71521]]
1220 Cost:  3.9182496 
Prediction:
 [[154.76416]
 [182.67863]
 [181.98097]
 [194.400