In [12]:
# 아래의 방법은 매트릭스를 사용하지 않고 구현되었음.
# 변수의 양이 늘어난다면 상당히 비효율적인 코드가 됨

In [13]:
import tensorflow as tf

In [2]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

In [3]:
y_data = [152., 185., 180., 196., 142.]


In [4]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [5]:
Y = tf.placeholder(tf.float32)

In [6]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [7]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b
print(hypothesis)

Tensor("add_2:0", dtype=float32)


In [8]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [9]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [10]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())


In [11]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  28249.531 
Prediction:
 [-0.28456834  7.148599    3.1358953   3.9081635   6.923118  ]
10 Cost:  3.183992 
Prediction:
 [148.39684 185.84056 179.21039 195.64795 143.21786]
20 Cost:  2.9113603 
Prediction:
 [148.85301 186.3769  179.74509 196.22931 143.62476]
30 Cost:  2.8974013 
Prediction:
 [148.86069 186.37424 179.74866 196.23228 143.62051]
40 Cost:  2.8834784 
Prediction:
 [148.867   186.36992 179.75063 196.2335  143.61504]
50 Cost:  2.869639 
Prediction:
 [148.8733  186.36565 179.75258 196.23473 143.60956]
60 Cost:  2.8558943 
Prediction:
 [148.87958 186.36136 179.75455 196.23595 143.60413]
70 Cost:  2.8422074 
Prediction:
 [148.88583 186.35709 179.75647 196.23715 143.59868]
80 Cost:  2.8285913 
Prediction:
 [148.89209 186.35283 179.75842 196.23836 143.59328]
90 Cost:  2.8150592 
Prediction:
 [148.8983  186.34859 179.76035 196.23955 143.58784]
100 Cost:  2.8016133 
Prediction:
 [148.9045  186.34435 179.76225 196.24074 143.58246]
110 Cost:  2.7882106 
Prediction:
 [148.9107  

1080 Cost:  1.7791665 
Prediction:
 [149.43904 185.97984 179.92851 196.34172 143.12042]
1090 Cost:  1.7712586 
Prediction:
 [149.44382 185.9766  179.93001 196.34262 143.11633]
1100 Cost:  1.7633873 
Prediction:
 [149.44858 185.97336 179.93149 196.34348 143.11224]
1110 Cost:  1.7555784 
Prediction:
 [149.45332 185.97014 179.93297 196.34438 143.10818]
1120 Cost:  1.7477875 
Prediction:
 [149.45805 185.9669  179.93443 196.34523 143.10411]
1130 Cost:  1.7400633 
Prediction:
 [149.46275 185.96368 179.9359  196.3461  143.10005]
1140 Cost:  1.732363 
Prediction:
 [149.46747 185.96048 179.93738 196.34697 143.09602]
1150 Cost:  1.7247188 
Prediction:
 [149.47215 185.95729 179.93883 196.34782 143.092  ]
1160 Cost:  1.7171049 
Prediction:
 [149.47684 185.95412 179.94029 196.34871 143.08797]
1170 Cost:  1.7095217 
Prediction:
 [149.4815  185.95093 179.94174 196.34955 143.08395]
1180 Cost:  1.7019947 
Prediction:
 [149.48616 185.94775 179.9432  196.3504  143.07997]
1190 Cost:  1.694505 
Prediction: