In [1]:
# 메모리가 클 경우 Queue Runners를 사용할 수 있다.
# 여러개의 파일을 Queue에 쌓고 Reader로 연결해서 Decoding 후 Queue에 쌓는다.
# 이후 Queue에서 하나씩 꺼내서 사용하게 된다.

# 1. 파일들의 리스트를 만들어 준다.
# 2. 파일을 읽어올 Reader를 정의한다. 그림에서는 TextLineReader를 사용했다.
# 3. value 값을 어떻게 decode 할것인가에 대해 알아본다.

In [2]:
import tensorflow as tf
tf.set_random_seed(777)  # for reproducibility


In [3]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')


In [4]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [5]:
# Default values, in case of empty columns. Also specifies the type of the
# decoded result.
record_defaults = [[0.], [0.], [0.], [0.]]
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [6]:
# collect batches of csv in
train_x_batch, train_y_batch = \
    tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)

In [7]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [8]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [9]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b


In [10]:
# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [11]:
# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [12]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [13]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

In [14]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)


0 Cost:  7070.9795 
Prediction:
 [[235.22784]
 [282.40146]
 [278.39618]
 [303.91577]
 [214.62396]
 [159.15425]
 [228.5351 ]
 [170.92644]
 [264.65048]
 [246.59116]]
10 Cost:  5.577785 
Prediction:
 [[154.65848]
 [185.555  ]
 [182.97673]
 [199.99612]
 [140.76091]
 [104.69594]
 [150.7493 ]
 [113.26346]
 [174.13757]
 [162.75192]]
20 Cost:  4.62937 
Prediction:
 [[154.11101 ]
 [184.90294 ]
 [182.33101 ]
 [199.2954  ]
 [140.26302 ]
 [104.333435]
 [150.22685 ]
 [112.87885 ]
 [173.53265 ]
 [162.19771 ]]
30 Cost:  4.618964 
Prediction:
 [[154.10362]
 [184.90007]
 [182.32486]
 [199.29121]
 [140.26024]
 [104.33596]
 [150.22578]
 [112.88076]
 [173.53444]
 [162.20546]]
40 Cost:  4.612851 
Prediction:
 [[154.09985]
 [184.90154]
 [182.32303]
 [199.29173]
 [140.26077]
 [104.34094]
 [150.22823]
 [112.88527]
 [173.54027]
 [162.21696]]
50 Cost:  4.606832 
Prediction:
 [[154.09615]
 [184.90303]
 [182.32123]
 [199.29228]
 [140.26134]
 [104.3459 ]
 [150.23068]
 [112.88977]
 [173.54611]
 [162.22844]]
60 Cost

540 Cost:  4.3902187 
Prediction:
 [[153.93523]
 [184.96678]
 [182.24254]
 [199.31676]
 [140.28282]
 [104.56153]
 [150.3405 ]
 [113.09155]
 [173.79984]
 [162.7298 ]]
550 Cost:  4.387138 
Prediction:
 [[153.93234]
 [184.96791]
 [182.24112]
 [199.31723]
 [140.28316]
 [104.56541]
 [150.34254]
 [113.0953 ]
 [173.80441]
 [162.7389 ]]
560 Cost:  4.38409 
Prediction:
 [[153.92944 ]
 [184.96902 ]
 [182.23969 ]
 [199.31769 ]
 [140.28348 ]
 [104.569275]
 [150.34457 ]
 [113.099045]
 [173.80896 ]
 [162.74792 ]]
570 Cost:  4.381089 
Prediction:
 [[153.92659]
 [184.97014]
 [182.23827]
 [199.31813]
 [140.2838 ]
 [104.57312]
 [150.3466 ]
 [113.10277]
 [173.81346]
 [162.75694]]
580 Cost:  4.3781157 
Prediction:
 [[153.92374]
 [184.97122]
 [182.23686]
 [199.31857]
 [140.28412]
 [104.57694]
 [150.3486 ]
 [113.10649]
 [173.81796]
 [162.7659 ]]
590 Cost:  4.3752093 
Prediction:
 [[153.92091]
 [184.97235]
 [182.23547]
 [199.31903]
 [140.28445]
 [104.58076]
 [150.35065]
 [113.11019]
 [173.82248]
 [162.77484]

1090 Cost:  4.2744036 
Prediction:
 [[153.79576]
 [185.01927]
 [182.1728 ]
 [199.33954]
 [140.29593]
 [104.74893]
 [150.44237]
 [113.27922]
 [174.02042]
 [163.17183]]
1100 Cost:  4.2731247 
Prediction:
 [[153.79355]
 [185.02008]
 [182.17169]
 [199.3399 ]
 [140.29608]
 [104.7519 ]
 [150.44403]
 [113.28231]
 [174.0239 ]
 [163.17886]]
1110 Cost:  4.2718987 
Prediction:
 [[153.79138]
 [185.0209 ]
 [182.1706 ]
 [199.3403 ]
 [140.29623]
 [104.75484]
 [150.44571]
 [113.28538]
 [174.02737]
 [163.18588]]
1120 Cost:  4.270661 
Prediction:
 [[153.7892  ]
 [185.02168 ]
 [182.16948 ]
 [199.34067 ]
 [140.29639 ]
 [104.75776 ]
 [150.44737 ]
 [113.288445]
 [174.0308  ]
 [163.19284 ]]
1130 Cost:  4.2694664 
Prediction:
 [[153.78703]
 [185.02246]
 [182.16838]
 [199.34103]
 [140.29652]
 [104.76068]
 [150.44902]
 [113.29149]
 [174.03424]
 [163.19977]]
1140 Cost:  4.268256 
Prediction:
 [[153.78488 ]
 [185.02324 ]
 [182.16728 ]
 [199.34138 ]
 [140.29668 ]
 [104.763565]
 [150.45065 ]
 [113.294525]
 [174.037

1640 Cost:  4.2334337 
Prediction:
 [[153.6901 ]
 [185.05649]
 [182.11853]
 [199.35829]
 [140.30069]
 [104.89143]
 [150.5259 ]
 [113.43352]
 [174.18823]
 [163.51385]]
1650 Cost:  4.233124 
Prediction:
 [[153.68843 ]
 [185.05702 ]
 [182.11765 ]
 [199.3586  ]
 [140.3007  ]
 [104.89368 ]
 [150.52725 ]
 [113.436035]
 [174.19087 ]
 [163.51927 ]]
1660 Cost:  4.232809 
Prediction:
 [[153.68677 ]
 [185.05757 ]
 [182.11678 ]
 [199.35889 ]
 [140.30072 ]
 [104.895905]
 [150.52861 ]
 [113.43857 ]
 [174.19348 ]
 [163.52469 ]]
1670 Cost:  4.2325506 
Prediction:
 [[153.68513 ]
 [185.05814 ]
 [182.11592 ]
 [199.3592  ]
 [140.30074 ]
 [104.89813 ]
 [150.52998 ]
 [113.441086]
 [174.19612 ]
 [163.53008 ]]
1680 Cost:  4.2322626 
Prediction:
 [[153.68349 ]
 [185.05869 ]
 [182.11507 ]
 [199.3595  ]
 [140.30075 ]
 [104.90033 ]
 [150.53134 ]
 [113.443596]
 [174.1987  ]
 [163.53543 ]]
1690 Cost:  4.232011 
Prediction:
 [[153.68185 ]
 [185.05922 ]
 [182.11421 ]
 [199.35982 ]
 [140.30077 ]
 [104.902534]
 [150.53

In [15]:
coord.request_stop()
coord.join(threads)

In [16]:
# Ask my score
print("Your score will be ",
      sess.run(hypothesis, feed_dict={X: [[100, 70, 101]]}))

print("Other scores will be ",
      sess.run(hypothesis, feed_dict={X: [[60, 70, 110], [90, 100, 80]]}))


Your score will be  [[185.3353]]
Other scores will be  [[178.36246]
 [177.03687]]
